from app.repositories.entities import (
    AssignmentRepository,
    CommentRepository,
    CourseRepository,
    EmailNotificationRepository,
    GradeRepository,
    GroupRepository,
    PermissionRepository,
    PlagiarismReportRepository,
    RefreshSessionRepository,
    RoleRepository,
    StudentRepository,
    SubmissionRepository,
    TestCaseRepository,
    TestResultRepository,
    UserRepository,
)

__all__ = [
    'AssignmentRepository',
    'CommentRepository',
    'CourseRepository',
    'EmailNotificationRepository',
    'GradeRepository',
    'GroupRepository',
    'PermissionRepository',
    'PlagiarismReportRepository',
    'RefreshSessionRepository',
    'RoleRepository',
    'StudentRepository',
    'SubmissionRepository',
    'TestCaseRepository',
    'TestResultRepository',
    'UserRepository',
]
